Repository Adi8080/Hactoberfest2021, pull requests merged in 2021-10, with the labels that each got.

#1 Update Contributers.md
  Contributers.md
Labels: hactoberfest-accepted

#8 Updated README file
  README.md
Labels: hactoberfest-accepted, hacktoberfest

#7 added links
  Contributers.md
Labels: hactoberfest-accepted

#13 Added Loop Detection in a Singly Linked List
  LoopDetectionInLinkedList.cpp
Labels: hacktoberfest-accepted

#14 added bubble sort algorithm using C
  bubble_sort.c
Labels: hacktoberfest, hacktoberfest-accepted

#18 Added algo to clone a linked list
  C_CPP_DSA/Linked_List/cloneLinkedList.cpp
Labels: hactoberfest-accepted, hacktoberfest

#35 Added balanced Paranthesis checker using Python
  Python_DSA/balanced-paranthesis.py
Labels: hacktoberfest, hacktoberfest-accepted
